name: CI

on: push

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip

    - name: Install dependencies
      run: |
        python scripts/ci/install
        python scripts/ci/install-build-system
        python -m pip freeze --all

    - name: Run build-system tests
      run: |
        pip uninstall -y awscli || true
        python scripts/ci/run-build-system-tests
